# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hongyihuang/Desktop/Berkeley/bringup/ram/ram.srcs/sources_1/ip/clk0/clk0.xci
# IP: The module: 'clk0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hongyihuang/Desktop/Berkeley/bringup/ram/ram.gen/sources_1/ip/clk0/clk0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hongyihuang/Desktop/Berkeley/bringup/ram/ram.gen/sources_1/ip/clk0/clk0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hongyihuang/Desktop/Berkeley/bringup/ram/ram.gen/sources_1/ip/clk0/clk0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hongyihuang/Desktop/Berkeley/bringup/ram/ram.srcs/sources_1/ip/clk0/clk0.xci
# IP: The module: 'clk0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hongyihuang/Desktop/Berkeley/bringup/ram/ram.gen/sources_1/ip/clk0/clk0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hongyihuang/Desktop/Berkeley/bringup/ram/ram.gen/sources_1/ip/clk0/clk0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hongyihuang/Desktop/Berkeley/bringup/ram/ram.gen/sources_1/ip/clk0/clk0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
